{{- if .Values.vpa.enabled}}
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: gardener-extension-os-gardenlinux-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: gardener-extension-os-gardenlinux
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode }}
  {{- if .Values.vpa.resourcePolicy }}
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          memory: {{ required "vpa.resourcePolicy.minAllowed.memory is required" .Values.vpa.resourcePolicy.minAllowed.memory }}
  {{- end }}
{{- end }}